testname: NWS Listening Test 2
testId: neural_waveshaping_synthesis_different_melody
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: false
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: >
        <p>Thank you for agreeing to take part in our short extra listening test. Please read these instructions carefully before continuing.</p>

        <p>In this section you will use the same interface as before. However, your task is slightly different.</p>

        <p>The reference is still a recording of an instrument playing a short melody. However, the conditions will contain recordings of a <em>different</em> melody.</p>

        <p>Your task is to rate the conditions in terms of how much they sound like the instrument you heard in the reference.</p>

        <hr />
        <p>
        When you are ready to continue, please click the button below.
        </p>
    # - type: headphone_check
    #   id: hc
    #   name: Headphone Check
    # - type: mushra
    #   id: trial1
    #   name: MUSHRA
    #   content: >
    #     <p>
    #     This training shows how to use our user interface.
    #     </p>
    #     <p>
    #     Please follow the below instructions to familiarise yourself with the interface.
    #     </p>
    #     <p>
    #     In this listening test, you are asked to rate the quality of each condition with respect to a reference.<br />
    #     To do so, first turn down your listening volume and start the reference playing by clicking the <em>Play</em> buton below
    #     the word <em>Reference</em>.<br />
    #     Now, adjust the volume until it is at a comfortable level.
    #     You can pause playback by clicking the button again, and pick up where you left off by clicking once more.<br />
    #     You can use the sliders below the waveform display to loop particular segments of the audio.<br />
    #     If you want to stop playback completely, you can use the stop button to the left of the screen.
    #     </p>
    #     <p>
    #     Now that you are familiar with the controls, try listening to the audio for the first condition by clicking the
    #     <em>Play</em> button below the text <em>Cond. 1</em>.<br />
    #     Then, use the slider below the button to rate the quality of the audio in terms of differences from the reference.<br />
    #     Try listening to and rating all the conditions this way, listening back to the reference as often as you need.<br />
    #     </p>
    #     <p>
    #     Once you are done, click <em>Next</em> to continue.
    #     </p>
    #   showWaveform: true
    #   enableLooping: true 
    #   reference: configs/resources/audio/mono_ref.wav
    #   createAnchor35: true
    #   createAnchor70: true
      # stimuli:
      #     C1: configs/resources/audio/mono_c1.wav
      #     C2: configs/resources/audio/mono_c2.wav
      #     C3: configs/resources/audio/mono_c3.wav
    - type: generic
      id: pre_study
      name: Ready
      content: >
        <p>
        You are now ready to begin the listening test.
        </p>
        <p>
        When you would like to start, please click <em>Next</em>
        </p>
    - 
          - random
          - type: mushra
            id: vn_1
            name: Multi-Stimulus Test
            content: Please rate the quality of the conditions with respect to the reference.
            enableLooping: true 
            reference: configs/resources/audio/nws-dm/vn1/vn1_dm_ref.wav
            createAnchor35: false
            createAnchor70: false
            createConditionAnchor1k: ref
            showWaveform: false
            randomize: true
            includeReference: false
            stimuli:
                htp: configs/resources/audio/nws-dm/vn1/vn1_dm_htp.wav
                ddsp_full: configs/resources/audio/nws-dm/vn1/vn1_dm_ddsp_full.wav
                ddsp_tiny: configs/resources/audio/nws-dm/vn1/vn1_dm_ddsp_tiny.wav
                nws: configs/resources/audio/nws-dm/vn1/vn1_dm_nws.wav
                nws_fn: configs/resources/audio/nws-dm/vn1/vn1_dm_nws_fn.wav
                ref: configs/resources/audio/nws-dm/vn1/vn1_dm_cond.wav
          - type: mushra
            id: tpt_1
            name: Multi-Stimulus Test
            content: Please rate the quality of the conditions with respect to the reference.
            enableLooping: true 
            reference: configs/resources/audio/nws-dm/tpt1/tpt1_dm_ref.wav
            createAnchor35: false
            createAnchor70: false
            createConditionAnchor1k: ref
            showWaveform: false
            randomize: true
            includeReference: false
            stimuli:
                htp: configs/resources/audio/nws-dm/tpt1/tpt1_dm_htp.wav
                ddsp_full: configs/resources/audio/nws-dm/tpt1/tpt1_dm_ddsp_full.wav
                ddsp_tiny: configs/resources/audio/nws-dm/tpt1/tpt1_dm_ddsp_tiny.wav
                nws: configs/resources/audio/nws-dm/tpt1/tpt1_dm_nws.wav
                nws_fn: configs/resources/audio/nws-dm/tpt1/tpt1_dm_nws_fn.wav
                ref: configs/resources/audio/nws-dm/tpt1/tpt1_dm_cond.wav
          - type: mushra
            id: fl_1
            name: Multi-Stimulus Test
            content: Please rate the quality of the conditions with respect to the reference.
            enableLooping: true 
            reference: configs/resources/audio/nws-dm/fl1/fl1_dm_ref.wav
            createAnchor35: false
            createAnchor70: false
            createConditionAnchor1k: ref
            showWaveform: false
            randomize: true
            includeReference: false
            stimuli:
                htp: configs/resources/audio/nws-dm/fl1/fl1_dm_htp.wav
                ddsp_full: configs/resources/audio/nws-dm/fl1/fl1_dm_ddsp_full.wav
                ddsp_tiny: configs/resources/audio/nws-dm/fl1/fl1_dm_ddsp_tiny.wav
                nws: configs/resources/audio/nws-dm/fl1/fl1_dm_nws.wav
                nws_fn: configs/resources/audio/nws-dm/fl1/fl1_dm_nws_fn.wav
                ref: configs/resources/audio/nws-dm/fl1/fl1_dm_cond.wav
    - type: finish
      name: Thank you
      content: >
        <p>Thank you for your participation!</p>
        <p>In order to save your results, please answer the following questions.</p>
      showResults: false
      writeResults: true
      questionnaire:
          - type: likert
            label: Age
            name: age
            response:
              - value: 18
                label: 18 - 29
              - value: 30
                label: 30 - 40
              - value: 40
                label: 40 - 50
              - value: 50
                label: 50 - 60
              - value: 60
                label: 60 - 70
              - value: 70
                label: 70+
          - type: likert
            name: gender
            label: What is your gender?
            response:
             - value: woman
               label: Woman
             - value: man
               label: Man
             - value: nonbinary
               label: Non-binary
             - value: undisclosed
               label: Prefer not to disclose
             - value: self-described
               label: Prefer to self describe
          - type: text
            name: self-described-gender
            label: If you prefer to self-describe, please do so
            optional: true
          - type: likert
            name: music_exp
            label: Which title best describes you?
            response:
             - value: nonmusician
               label: Nonmusician
             - value: music_loving_nonmusician
               label: Music Loving Nonmusician
             - value: amateur_musician
               label: Amateur Musician
             - value: serious_amateur_musician
               label: Serious Amateur Musician
             - value: semi_professional_musician
               label: Semi-professional Musician
             - value: professional_musician
               label: Professional Musician
          - type: likert
            name: audio_exp
            label: Which title best describes your experience with music or audio production?
            response:
             - value: no_experience
               label: No experience
             - value: amateur
               label: Amateur
             - value: serious_amateur
               label: Serious Amateur
             - value: semi-professional
               label: Semi-professional
             - value: professional
               label: Professional